"""Gemini-powered secondary validation pass (LLM-as-Judge).

Output is advisory only — labelled "CANDIDATE FLAGS — FOR HUMAN REVIEW".
The primary AuditAgent (Claude) is the authoritative classifier.
"""
from __future__ import annotations

import json
import re
from typing import Optional

from langchain_core.messages import HumanMessage, SystemMessage

from ..core.llm import get_llm
from .prompts import JUDGE_SYSTEM_PROMPT, JUDGE_USER_TEMPLATE


class JudgeAgent:
    """Secondary hallucination detector using Gemini (free tier).

    Inputs: transcript + AI output + ground truth
    Outputs: list of candidate flag dicts, each with:
        - field, observation, confidence, hallucination_type
    """

    def __init__(self, llm=None) -> None:
        self._llm = llm or get_llm()

    def evaluate(
        self,
        transcript: str,
        ai_output: dict,
        ground_truth: dict,
    ) -> dict:
        """Run a secondary validation pass and return candidate flags.

        Returns a dict with:
            - candidate_flags: list of flag dicts
            - advisory_note: disclaimer string
        """
        user_content = JUDGE_USER_TEMPLATE.format(
            transcript=transcript,
            ai_output=json.dumps(ai_output, indent=2, ensure_ascii=False),
            ground_truth=json.dumps(ground_truth, indent=2, ensure_ascii=False),
        )

        messages = [
            SystemMessage(content=JUDGE_SYSTEM_PROMPT),
            HumanMessage(content=user_content),
        ]

        response = self._llm.invoke(messages)
        raw_text: str = response.content if hasattr(response, "content") else str(response)

        candidate_flags = self._parse_flags(raw_text)
        return {
            "candidate_flags": candidate_flags,
            "advisory_note": "CANDIDATE FLAGS — FOR HUMAN REVIEW. Generated by Gemini secondary pass.",
            "raw_response": raw_text,
        }

    async def aevaluate(
        self,
        transcript: str,
        ai_output: dict,
        ground_truth: dict,
    ) -> dict:
        """Async variant."""
        user_content = JUDGE_USER_TEMPLATE.format(
            transcript=transcript,
            ai_output=json.dumps(ai_output, indent=2, ensure_ascii=False),
            ground_truth=json.dumps(ground_truth, indent=2, ensure_ascii=False),
        )
        messages = [
            SystemMessage(content=JUDGE_SYSTEM_PROMPT),
            HumanMessage(content=user_content),
        ]
        response = await self._llm.ainvoke(messages)
        raw_text: str = response.content if hasattr(response, "content") else str(response)
        candidate_flags = self._parse_flags(raw_text)
        return {
            "candidate_flags": candidate_flags,
            "advisory_note": "CANDIDATE FLAGS — FOR HUMAN REVIEW. Generated by Gemini secondary pass.",
            "raw_response": raw_text,
        }

    @staticmethod
    def _parse_flags(text: str) -> list[dict]:
        """Extract a JSON array from the model response, with graceful fallback."""
        match = re.search(r"\[[\s\S]*\]", text)
        if match:
            try:
                flags = json.loads(match.group())
                if isinstance(flags, list):
                    return flags
            except json.JSONDecodeError:
                pass
        # Return raw text wrapped so callers always get a list
        return [{"raw_text": text, "parse_error": "Could not extract JSON array from judge response"}]
