from typing import Optional, List
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage
from src.core.llm import get_llm 
from langchain_community.chat_message_histories import ChatMessageHistory
from langchain_classic.memory import ConversationSummaryBufferMemory

class MemoryManager:
    """
    Memory Manager for managing conversation history and summaries.
    """

    def __init__(
        self,
        llm: Optional[object] = None,
        max_token_limit: int = 2000,
        memory_key: str = "history",
    ):
        """
        Initialize the memory manager.

        Args:
            llm: LangChain Chat model used for generating summaries.
            max_token_limit: Maximum token limit, automatically triggers summarization when exceeded.
            memory_key: The key name used to store conversation history in memory.
        """
        self._llm = llm or get_llm()
        self._max_token_limit = max_token_limit
        self._memory_key = memory_key
        self._memory = self._create_memory()

    def _create_memory(self) -> ConversationSummaryBufferMemory:
        """
        Create a memory instance.
        """
        return ConversationSummaryBufferMemory(
            llm=self._llm,
            max_token_limit=self._max_token_limit,
            memory_key=self._memory_key,
            return_messages=True,
        )

    @property
    def memory(self) -> ConversationSummaryBufferMemory:
        """
        Get the memory instance.
        """
        return self._memory

    def add_user_message(self, message: str) -> None:
        """
        Add a user message to memory.
        """
        self._memory.chat_memory.add_user_message(message)

    def add_ai_message(self, message: str) -> None:
        """
        Add an AI message to memory.

        Args:
            message: The message content generated by the AI.
        """
        self._memory.chat_memory.add_ai_message(message)

    def get_history(self) -> list:
        """
        Get the conversation history.

        Returns:
            list: A list of raw conversation messages [HumanMessage/AIMessage].
        """
        return self._memory.load_memory_variables({}).get(self._memory_key, [])

    def clear(self) -> None:
        """
        Clear all conversation memory.
        """
        self._memory.clear()
    def get_context(self) -> str:
        """
        Get the formatted conversation context.

        Convert conversation history into a readable string format.

        Returns:
            str: Formatted conversation context.
        """
        history = self.get_history()
        if not history:
            return ""

        context_parts = []
        for msg in history:
            if isinstance(msg, HumanMessage):
                context_parts.append(f"User: {msg.content}")
            elif isinstance(msg, AIMessage):
                context_parts.append(f"AI: {msg.content}")
            else:
                context_parts.append(str(msg))

        return "\n".join(context_parts)


def get_memory_manager(**kwargs) -> MemoryManager:
  """
  Factory function to get a MemoryManager instance.

  Args:
      **kwargs: Arguments passed to MemoryManager.

  Returns:
      MemoryManager: Configured MemoryManager instance.
  """
  return MemoryManager(**kwargs)